### ISSUE TITLE
Front End fails to come up when running the bootstrap steps in "Start The Workshop"

### ISSUE THREAD

**Issue by dgwalters** [aws-containers/appmeshworkshop#17]
The EC2 instances fail to start the Rails app due to the following error in the user data logs (/var/log/user-data.log):

```
/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/resolver/conflict.rb:47:in `conflicting_dependencies': undefined method `request' for nil:Nil
Class (NoMethodError)
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/exceptions.rb:61:in `conflicting_dependencies'
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/exceptions.rb:55:in `initialize'
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/resolver.rb:193:in `exception'
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/resolver.rb:193:in `raise'
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/resolver.rb:193:in `rescue in resolve'
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/resolver.rb:189:in `resolve'
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/request_set.rb:411:in `resolve'
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/request_set.rb:423:in `resolve_current'
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:230:in `finish_resolve'
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:287:in `block in activate_bin_path'
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:285:in `synchronize'
from /.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:285:in `activate_bin_path'
from /.rbenv/versions/2.5.1/bin/rails:25:in `<main>'
```
I manually ran the user data script as root and get the same error. Any attempt to run `rails` produces the same error, even `rails -v`

**Comment by berry2012** [comment]
Faced same issue.
even tried:
`rbenv install 2.6.5 && rbenv global 2.6.5`


```
/root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:317:in `raise_error_unless_state': Unable to satisfy the following requirements: (Gem::Resolver::Molinillo::VersionConflict)

- `activesupport (= 7.0.2.3)` required by `user-specified dependency`
        13: from /root/.rbenv/versions/2.6.5/bin/rails:25:in `<main>'
        12: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:285:in `activate_bin_path'
        11: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:285:in `synchronize'
        10: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:287:in `block in activate_bin_path'
         9: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:230:in `finish_resolve'
         8: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:423:in `resolve_current'
         7: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:411:in `resolve'
         6: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/resolver.rb:191:in `resolve'
         5: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/resolver.rb:193:in `rescue in resolve'
         4: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/resolver.rb:193:in `raise'
         3: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/resolver.rb:193:in `exception'
         2: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/exceptions.rb:55:in `initialize'
         1: from /root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/exceptions.rb:61:in `conflicting_dependencies'
/root/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/resolver/conflict.rb:47:in `conflicting_dependencies': undefined method `request' for nil:NilClass (NoMethodError)
```
